apiVersion: v1
kind: Pod
metadata:
  name: myflask-pod
  labels:
    app: myflask
spec:
  containers:
    - name: myflask-container
      image: lena2017/myflaskapp:01
      ports:
        - containerPort: 5000

